### ISSUE TITLE
name conflicts with neovim

### ISSUE THREAD

**Issue by eprislac** [cwoac/nvvim#46] opened 2018-03-20 17:45 UTC
The name `nvim` conflicts with the command to run `neovim`... maybe consider a name-change to nv-vim?

**Comment by cwoac** [comment] 2018-05-13 14:59
Duplicate of #41

**Comment by leojpod** [comment] 2018-07-04 11:14
I know you closed these issues 'cause nvim predates neovim but objectively speaking, using nvim for this project is shadowing it on all web search engine since neovim is wide spread and commonly abbreviated by nvim...

**Comment by leojpod** [comment] 2018-07-13 11:29
Sorry about it ...

**Comment by cwoac** [comment] 2018-07-18 09:17
Done in 31db19a5f3cae71b109bb80dc8ed1885599ada6f

**Closed by cwoac** 2018-07-18 09:17 UTC
